### ISSUE TITLE
Crypto lib API to allow a "secure mode" where OpenSPDM does not see ephemeral keys

### ISSUE THREAD

**Issue by xiaoyuruan** [jyao1/openspdm#101]
Some implementations require minimum TCB such that FW processes such as OpenSPDM avoids visibility of not only persistent keys (certificate private key, PSK, Handshake-Secret), but also ephemeral keys:
- ECDH private key
- All secrets in Key Schedule

The crypto library (may be FW, SW, or most commonly, HW) should provide APIs for OpenSPDM to 
- Generate ECDH keypair using internal RNG.  The generated private key returned to caller (OpenSPDM) may be raw key value or a handle.
- HMAC-hash.  Input HMAC key may be value or a handle.  Output may be raw value or a handle (if output is used as a key; caller needs to specify output key type HMAC or AES).
- HKDF-Expand.  Input HMAC key may be value or a handle.  Output may be raw key value or a handle (caller needs to specify output key type HMAC or AES).

If the underlying crypto lib supports the "handle" options for above APIs, then OpenSPDM must be compiled as "secure mode" and use the "handle" option of above crypto APIs.  If crypto lib does not support "handle" option, then OpenSPDM cannot use "secure mode".

Security model: OpenSPDM may still access values of ephemeral keys (by asking crypto library to output "raw value" when calling above APIs).  In other words, if attacker gains execution privilege of OpenSPDM, he/she could see the key values.  This is OK, because with execution privilege he/she could invoke and use ephemeral keys anyway.  The secure mode protects ephemeral keys if attacker managed to gain read privilege of OpenSPDM.

**Comment by jyao1** [comment]
isolate all session keys to SpdmSecuredMessageLib.

SpdmCommonLib/ResponderLib/RequesterLib cannot see the session keys.

**Comment by jyao1** [comment]
See https://github.com/jyao1/openspdm/blob/master/Doc/ThreatModel.md
