### ISSUE TITLE
Do we need include Opaque data for MeasurementResponse without signature?

### ISSUE THREAD

**Issue by jyao1** [jyao1/openspdm#141]
See #137, test case feedback 3.

TestSpdmRequesterGetMeasurement fail due to one of the following reasons:
Opaque data is ignored if the measurement response does not include a signature (test cases 23, 24, 29)

Current code purposely ignored Opaque data, because I don't think we should transport Opaque data if no signature is required.

Maybe SPDM spec should clarify it.

**Comment by xiaoyuruan** [comment]
SPDM does not specify that signature is a pre-requisite of Opaque Data in MEASUREMENT response.  So Opaque Data should be included.  The Requester should decide whether to use Responder's Opaque Data without a signature or send GET_MEASUREMENT again but require a signature.

**Comment by t-koulouris** [comment]
agree with @xiaoyuruan

**Comment by jyao1** [comment]
Fixed after fdb1467fc9d32504f0d101d77fa7c99be2dec26c.
Case 23/24/29 are enabled.
