### ISSUE TITLE
How to use the default openssl-1.1.1g installation path to make a build?

### ISSUE THREAD

**Issue by chenxizf** [jyao1/openspdm#176]
Hi,

I am able to successfully build SPDM on Linux by issuing the command below:
"make -f GNUmakefile ARCH=X64 TARGET=DEBUG CRYPTO=Openssl -e WORKSPACE=~/openspdm-master"

However, can I know how I can use the openssl-1.1.1g that is installed under its default installation path (e.g /usr/bin and /usr/include/openssl) instead of hard-copying again the openssl folder into OpensslLib?
The reason why I am doing that is because we already installed openssl-1.1.1g on Linux, and would like to use that and avoid copying it again to SPMD build.

Thank you!

**Comment by rcaalves** [comment]
Hello,

AFAIK, you need Openssl sources to compile openspdm. Just the headers and precompiled binary is not enough.
If you have the sources somewhere else, you can try to symlink it to the indicated path.

**Comment by jyao1** [comment]
This is not supported in current makefile.

If you work out a solution, please submit a patch. We can integrate it.

**Comment by jyao1** [comment]
Similar to https://github.com/jyao1/openspdm/issues/178.

Binary build support is tracked in https://github.com/DMTF/libspdm/issues/25
