### ISSUE TITLE
All requests should use SPDM_MESSAGE_VERSION_11

### ISSUE THREAD

**Issue by xiaoyuruan** [jyao1/openspdm#4]
With exception of GET_VERSION, all requests and responses should use SPDM_MESSAGE_VERSION_11 in header, even though those commands were first defined in 1.0.

**Comment by jyao1** [comment]
The Requester need check the version number returned from the responder and choose highest supported version to send the command. For example, if the responder supports version 1.1, the requester should use GET_CAPABIILTY 1.1 version (with CTExponent/flags). If the responder supports version 1.0, then the requester should use GET_CAPABILITY 1.0 version (without CTExponent/flags)

**Comment by jyao1** [comment]
Duplicated with https://github.com/jyao1/openspdm/issues/8

**Comment by jyao1** [comment]
fixed in b8269a519377093b4453ab3ec4752b9eb2e12594
