### ISSUE TITLE
MANAGED_BUFFER, LARGE_MANAGED_BUFFER, SMALL_MANAGED_BUFFER

### ISSUE THREAD

**Issue by xiaoyuruan** [jyao1/openspdm#6]
The code requires that MANAGED_BUFFER be the same as the first two components of LARGE/SMALL_MANAGED_BUFFER.
To facilitate such, suggest below:

typedef struct {
  UINTN   MaxBufferSize;
  UINTN   BufferSize;
//UINT8   Buffer[MaxBufferSize];
} MANAGED_BUFFER;

typedef struct {
  **MANAGED_BUFFER ManagedBufferSizes;**
  UINT8   Buffer[MAX_SPDM_MESSAGE_BUFFER_SIZE];
} LARGE_MANAGED_BUFFER;

typedef struct {
  **MANAGED_BUFFER ManagedBufferSizes;**
  UINT8   Buffer[MAX_SPDM_MESSAGE_SMALL_BUFFER_SIZE];
} SMALL_MANAGED_BUFFER;

**Comment by jyao1** [comment]
tracked in https://github.com/DMTF/libspdm/issues/33
