### ISSUE TITLE
Function of SpdmGetVersion()

### ISSUE THREAD

**Issue by xiaoyuruan** [jyao1/openspdm#8]
I think instead of returning list of Responder's supported versions to caller, function SpdmGetVersion() itself should do the comparison of its own version (currently 1.1) and Responder's supported versions and decides on the highest common version to use going forward.

**Comment by jyao1** [comment]
duplicated with https://github.com/jyao1/openspdm/issues/4

**Comment by jyao1** [comment]
fixed in b8269a519377093b4453ab3ec4752b9eb2e12594
