### ISSUE TITLE
Synchronous and Asynchronous application message passing

### ISSUE THREAD

**Issue by raghuncstate** [jyao1/openspdm#98]
Opening an issue based on the walkthrough meeting we had on 12/10/2020. To support application use cases such as FW update, where there is bi-direction and Asynchronous message passing, the secured message library(or whatever is appropriate) needs to provide an API to the application to send messages and be able to receive messages asynchronously. DSP0274 has keys for each direction of communication within a session and must be appropriately used for sending and receiving messages. The example cited was for PLDM for FW update. During PLDM for FW update(DSP0267), a BMC initiates the update state machine using messages from the spec but the device being updated(called firmware device/FD), downloads/pulls the firmware image from the BMC. So during the application phase of the SPDM protocol, there will be full duplex communication.

Without designing the solution, a strawman proposal for API would be:

1) SendReceiveData() - Application calls this API to send its data and receive data. SPDM layer will use the sender direction key on application data to secure it and send it over transport. It will then pend/wait using an environment dependent mechanism(polling or OS api's) for a response from the receiver of the message. When the response arrives, the SPDM layer applies the response direction key and returns the application data to the caller.

2) SendData() - Application calls this API to send its data and receive data. SPDM layer will use the sender direction key on application data to secure it and send it over transport. The API immediately returns to the caller.

3) ReceiveData() - Application calls this API to pend/wait using an environment dependent mechanism(polling or OS api's) for a response from the receiver of the message. When the response arrives, the SPDM layer applies the response direction key and returns the application data to the caller.

Optionally, the library can provide an API to the application to register a call back for when there is a message that arrives for a particular session context.

**Comment by jyao1** [comment]
SendData() and ReceiveData() are exposed in SpdmRequesterLib.
SpdmProcessRequest() and SpdmBuildResponse() are exposed in SpdmResponderLib.
