### ISSUE TITLE
Make PSK and Handshake-Secret values invisible to OpenSPDM

### ISSUE THREAD

**Issue by xiaoyuruan** [jyao1/openspdm#99]
As a general security hardening practice, OpenSPDM should not know the values of persistent secrets, including PSK (Pre-Shared Key) and Handshake-Secret.  Similar to private key of certificate, the PSK and Handshake-Secret should be kept in the crypto library or a key store module.

According to SPDM 1.1 Key Schedule, the PSK is only used in HMAC-Hash as message (key of HMAC is 00..00) to generate Handshake-Secret.  i.e., both PSK and Handshake-Secrets are constant/persistent on a Requester or Responder device.  OpenSPDM does not need to invoke PSK, it only needs to invoke Handshake-Secret for HKDF-Expand / HMAC operation.  

Bottom-line:  The crypto lib / key store module should expose an API "HkfdExpandWithHandshakeSecret", which does not ask caller to pass in PRK but uses Handshake-Secret as PRK.  The output is returned to the caller in the clear.  PRK is calculated from PSK as specified by SPDM 1.1 Key Schedule.

**Comment by jyao1** [comment]
Update code to remove PSK from SPDM Context. See UserGuide.md:

   1.6, if PSK is required, register PSK HMAC function, and optionally deploy PSK Hint.
   ```
   SpdmRegisterDataSignFunc (SpdmContext, SpdmPskHmacFunc);
   SpdmSetData (SpdmContext, SpdmDataPskHint, NULL, PskHint, PskHintSize);
   ```

**Comment by jyao1** [comment]
Handshake-Secret is not persistent. It is one time, and negotiated in session. It will be handled in https://github.com/jyao1/openspdm/issues/101.

**Comment by xiaoyuruan** [comment]
> Handshake-Secret is not persistent. It is one time, and negotiated in session. It will be handled in #101.

According to the first step in the figure at paragraph 586 of https://www.dmtf.org/sites/default/files/standards/documents/DSP0274_1.1.0.pdf, Handshake-Secret = HMAC-hash(Salt_0, PSK), which is a constant because both Salt_0 and PSK are constant.

**Comment by jyao1** [comment]
Ok. bin_str0 is a constant. Then Salt1 = HKDF-Expand ( Handshake-Secret, bin_str0, Hash.Length ) is constant.
Then Master-Secret = HMAC-Hash ( Salt_1, 0_filled ) is also constant.

To hide those information, we need refine the API to expose HKDF to return:
1) Request Direction Handshake Secret
2) Response Direction Handshake Secret
3) Request Direction Data Secret
4) Response Direction Data Secret
5) Export Master Secret

**Comment by jyao1** [comment]
Now openspdm doesn't generate Psk, HandshakeSecret, and MasterSecret at all.


   1.6, if PSK is required, register PSK HKDF_EXPAND function, and optionally deploy PSK Hint.
   ```
   SpdmRegisterPskHkdfExpandFunc (SpdmContext, SpdmPskHandshakeSecretHkdfExpandFunc, SpdmPskMasterSecretHkdfExpandFunc);
   SpdmSetData (SpdmContext, SpdmDataPskHint, NULL, PskHint, PskHintSize);
   ```
